server:
  port: 20301
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttg_database
    username: dbadmin
    password: dbmanager
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        default_schema: ttg_service
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
jwt:
  secret: etSit/ixkWVvFwre069WTKlRnEQn4PDrrd8qfnMcAuogsocH0X/8tRXhY2ved8GKDIekK1jIs027OfaoUQlY7Q==